[colors]
background = '#191a1c'
foreground = '#bcbec4'
selection-background = '#2a4371'
selection-foreground = '#d1d3d9'
cursor = '#bcbec4'
black = '#191a1c'
red = '#e4656e'
green = '#4e9d6c'
yellow = '#c28013'
blue = '#538af9'
magenta = '#967bef'
cyan = '#4b9b93'
white = '#bcbec4'
light_black = '#73767c'
light_red = '#f57e84'
light_green = '#6db083'
light_yellow = '#d59637'
light_blue = '#71a1fe'
light_magenta = '#a894f6'
light_cyan = '#6aaea6'
light_white = '#ffffff'
